# Form implementation generated from reading ui file 'd:\14_06_original\day25.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 703)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_videoframe = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_videoframe.setGeometry(QtCore.QRect(30, 60, 800, 450))
        self.label_videoframe.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.label_videoframe.setObjectName("label_videoframe")
        self.button_openfile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_openfile.setGeometry(QtCore.QRect(30, 550, 113, 32))
        self.button_openfile.setObjectName("button_openfile")
        self.label_framecnt = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_framecnt.setGeometry(QtCore.QRect(660, 560, 171, 21))
        self.label_framecnt.setObjectName("label_framecnt")
        self.button_play = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_play.setGeometry(QtCore.QRect(710, 600, 113, 32))
        self.button_play.setObjectName("button_play")
        self.button_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(400, 600, 113, 32))
        self.button_stop.setObjectName("button_stop")

        ######################
        self.button_procesar_caras = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_procesar_caras.setGeometry(QtCore.QRect(90, 600, 113, 32))
        self.button_procesar_caras.setObjectName("button_procesar_caras")
        ######################

        self.label_filepath = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_filepath.setGeometry(QtCore.QRect(40, 650, 811, 41))
        self.label_filepath.setObjectName("label_filepath")
        self.button_pause = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_pause.setGeometry(QtCore.QRect(560, 600, 113, 32))
        self.button_pause.setObjectName("button_pause")
        self.button_procesar_rostros = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_procesar_rostros.setGeometry(QtCore.QRect(240, 600, 113, 32))
        self.button_procesar_rostros.setObjectName("button_procesar_rostros")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_videoframe.setText(_translate("MainWindow", "video_player"))
        self.button_openfile.setText(_translate("MainWindow", "Openfile"))
        self.label_framecnt.setText(_translate("MainWindow", "current_frame/total_frame"))
        self.button_play.setText(_translate("MainWindow", "Play"))
        self.button_stop.setText(_translate("MainWindow", "Stop"))
        self.label_filepath.setText(_translate("MainWindow", "file path:"))
        self.button_pause.setText(_translate("MainWindow", "Pause"))
        ###
        self.button_procesar_rostros.setText(_translate("MainWindow", "Procesar rostros"))
        ###